version: '3'
services:
  web:
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=ctf_user
      - MYSQL_PASSWORD=ctf_pass
      - MYSQL_DATABASE=ctf_db

  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=ctf_db
      - MYSQL_USER=ctf_user
      - MYSQL_PASSWORD=ctf_pass
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
